import '../app/globals.css';
import Navbar from '../components/Navbar';
import type { ReactNode } from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Personal App',
  description: 'Generated by Codex',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className="min-h-screen bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100">
        <div className="min-h-screen flex flex-col">
          <Navbar />
          <main className="flex-grow p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
